name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: 13 23 * * *

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t fluree/crypto .
      - name: Run CLJ tests
        run: script/run-in-docker.sh lein test
      - name: Run CLJS tests
        run: script/run-in-docker.sh npm run ci-cljs